# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Doze < Formula
  desc "Real databases on your laptop — asleep until you need them"
  homepage "https://doze.nerdmenot.in"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/doze-dev/doze/releases/download/v0.1.0/doze_0.1.0_darwin_arm64.tar.gz"
      sha256 "92a04e1ddcab3645dce715f1d0663a19ef40d265281fa9910d41d7d7f85290e2"

      define_method(:install) do
        bin.install "doze"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/doze-dev/doze/releases/download/v0.1.0/doze_0.1.0_linux_amd64.tar.gz"
      sha256 "d9b6957d241f085da86583b251943ef57cab8b07a9aae63ee6365ccfbd74bed4"
      define_method(:install) do
        bin.install "doze"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/doze-dev/doze/releases/download/v0.1.0/doze_0.1.0_linux_arm64.tar.gz"
      sha256 "61d3e98bb0b78230dd3bbf5da9746b1bbd6b68dfd59ce7a015d89f04787dd97a"
      define_method(:install) do
        bin.install "doze"
      end
    end
  end

  test do
    system "#{bin}/doze", "version"
  end
end
